apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: amorphie-login-set-new-password
spec:
  type: bindings.zeebe.jobworker
  version: v1
  metadata:
  - name: jobType
    value: amorphie-login-set-new-password
  - name: gatewayAddr
    value: localhost:26500
  - name: gatewayKeepAlive
    value: 45s
  - name: usePlainTextConnection
    value: true