apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: amorphie-ekyc-nfc-check
spec:
  type: bindings.zeebe.jobworker
  version: v1
  metadata:
  - name: jobType
    value: amorphie-ekyc-nfc-check
  - name: gatewayAddr
    value:  10.180.141.16:30499
  - name: gatewayKeepAlive
    value: 45s
  - name: usePlainTextConnection
    value: true