apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: amorphie-token-check-grant-type
  namespace: amorphie-token
spec:
  type: bindings.zeebe.jobworker
  version: v1
  metadata:
  - name: jobType
    value: amorphie-token-check-grant-type
  - name: gatewayAddr
    value: zeebe-zeebe-gateway.amorphie-zeebe.svc.cluster.local:26500
  - name: gatewayKeepAlive
    value: 45s
  - name: usePlainTextConnection
    value: true