apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: amorphie-cache
  namespace: amorphie-token
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "redis-host"
  - name: redisPassword
    secretKeyRef:
      name: redis-secret
      key: redis-password
  - name: actorStateStore
    value: "true"
  - name: redisType
    value: "cluster"
  - name: keyPrefix
    value: name
auth:
  secretStore: user-secretstore
