name: CI-CD-API
on:
  push:
    branches: [ main ]
    paths:
      - 'src/Api/**'
      - 'src/Application/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/Api/**'
      - 'src/Application/**'
  workflow_dispatch:

env:
  APP_NAME: amorphie.mocks
  NAMESPACE: amorphie-mocks
  CLUSTER_NAME: BurganAKS
  CLUSTER_RESOURCE_GROUP: BurganTech
  SECRET: docker-hub

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./amorphie.mocks/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}

      # Set the target Azure Kubernetes Service (AKS) cluster. 
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
      # Create namespace if doesn't exist
      - run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -
    
      # Create image pull secret for Docker
      - uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: docker.io
          container-registry-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          container-registry-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          secret-name: ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
          arguments: --force true

      # Deploy app to AKS
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            ${{ github.workspace }}/amorphie.mocks/manifest/deployment.yaml
            ${{ github.workspace }}/amorphie.mocks/manifest/service.yaml
            ${{ github.workspace }}/amorphie.mocks/manifest/ingress.yaml
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
