name: TOKEN-CI-CD-API
on:
  push:
    branches: [ main, LoginFlow ]
  pull_request:
    branches: [ main, LoginFlow ]
  workflow_dispatch:
env:
  APP_NAME: amorphie.token
  NAMESPACE: amorphie-token
  CLUSTER_NAME: BurganAKS
  CLUSTER_RESOURCE_GROUP: BurganTech
  SECRET: docker-hub

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-Token
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}

      # Set the target Azure Kubernetes Service (AKS) cluster. 
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    
      # Create image pull secret for Docker
      - uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: docker.io
          container-registry-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          container-registry-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          secret-name: ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
          arguments: --force true

      - name: Replace redis-host
        run: |
          sed -i -e "s/redis-host/${{ secrets.REDIS_HOST }}/g" ./manifest/dapr/cache-redis-component.yaml
          
      - name: Replace vault address
        run: |
          sed -i -e "s,vault-address,${{ secrets.VAULT_ADDRESS }},g" ./manifest/dapr/vault-component.yaml

      - name: Replace vault token
        run: |
          sed -i -e "s,amorphie-vaulttoken,${{ secrets.VAULT_TOKEN }},g" ./manifest/dapr/vault-component.yaml

      # Deploy app to AKS
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            ${{ github.workspace }}/manifest/deployment.yaml
            ${{ github.workspace }}/manifest/dapr/cache-redis-component.yaml
            ${{ github.workspace }}/manifest/dapr/vault-component.yaml
            ${{ github.workspace }}/manifest/dapr/amorphie-zeebe-command.yaml
            ${{ github.workspace }}/manifest/dapr/amorphie-zeebe-fact-check-grant-type.yaml
            ${{ github.workspace }}/manifest/dapr/amorphie-zeebe-fact-check-scopes.yaml
            ${{ github.workspace }}/manifest/dapr/amorphie-zeebe-fact-check-user-state.yaml
            ${{ github.workspace }}/manifest/dapr/amorphie-zeebe-fact-check-user.yaml
            ${{ github.workspace }}/manifest/dapr/amorphie-zeebe-fact-validate-client.yaml
            ${{ github.workspace }}/manifest/dapr/amorphie-zeebe-token-check-otp.yaml
            ${{ github.workspace }}/manifest/dapr/amorphie-zeebe-token-generate-tokens.yaml
            ${{ github.workspace }}/manifest/dapr/amorphie-zeebe-token-otp-login-flow.yaml
            ${{ github.workspace }}/manifest/dapr/amorphie-zeebe-token-set-state.yaml
            ${{ github.workspace }}/manifest/service.yaml
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
 
